PRI_NET_RANGE: "192.168.1."
PRI_NET_CARD: "ppp0"
PRI_NET_MOLD: "PPP"
PUB_NET_CARD: "eth0"
PUB_GW_HOST_IP: "10.6.4.1"
MOCK_GW_PORT: 12321
DUMMY_NAT_TYPE: "2"
CHANGE_DATA_EVENT: False
CHANGE_DATA_NOT_RANDOM: False
CHANGE_DATA_POSITION: 1
CHANGE_DATA_OPERATOR: "&"
CHANGE_DATA_OPERATE_DATA: 15
CHANGE_DATA_COUNT: 1
CHANGE_DATA_CONTAIN: []